### PR TITLE
Update Cucumber to 4.2.6 (#309)

### PR DESCRIPTION
**Pull request by mkrzyzanowski**
- Cleaned up the bobcat-bdd template
- Added cucumber Gradle task so tests are now run via CLI, not JUnit

### CODE REVIEW

**Comment by DeChrish** [comment]
@mkrzyzanowski we need to wait for the release right? https://github.com/Cognifide/bobcat/issues/309

**Comment by mkrzyzanowski** [comment]
Well, not this time :). As you can see, the changes include removing `bb-cumber` and adding Cucumber deps. Migration process is described here https://cognifide.github.io/bobcat/docs/cucumber/#migrating-from-previous-versions-bb-cumber

**Comment by DeChrish** [comment]
**def bobcatVersion = '2.0.4-SNAPSHOT' !!!**

Latest cucumber ver. migration in available in snapshot, do i need to build bobcat in local to get the latest snapshot or bobcat snapshot is available in maven central?

https://github.com/Cognifide/bobcat-gradle-template/issues/19

**Comment by mkrzyzanowski** [comment]
Bah, copy-paste error, I've fixed the doc :). There's no snapshot version available, just use the latest available (2.0.3)

**Pull request merged**
